################################################################################
# The MIT License
#
# Copyright (c) 2021, Prominence AI, Inc.
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.
################################################################################

#!/usr/bin/env python

import tkinter as tk

BUTTON_SIDE_LENGTH = 48
BUTTON_FRAME_SIDE_LENGTH = 56

ACTION_ROW_Y_OFFSET = 10   # from top of Window to top of frame
STATUS_ROW_Y_OFFSET = 64  # from bottom of Window to top of frame

COLOR_PICKER_FRAME_X_OFFSET = 64
COLOR_PICKER_FRAME_Y_OFFSET = ACTION_ROW_Y_OFFSET

COLORS_ROW_1_FRAME_X_OFFSET = COLOR_PICKER_FRAME_X_OFFSET + 296
COLORS_ROW_1_FRAME_Y_OFFSET = ACTION_ROW_Y_OFFSET + 2

COLORS_ROW_2_FRAME_X_OFFSET = COLOR_PICKER_FRAME_X_OFFSET + 296
COLORS_ROW_2_FRAME_Y_OFFSET = ACTION_ROW_Y_OFFSET + 27

BG_COLOR_FRAME_X_OFFSET = COLORS_ROW_2_FRAME_X_OFFSET + 64
BG_COLOR_FRAME_Y_OFFSET = ACTION_ROW_Y_OFFSET + 2

LINE_COLOR_FRAME_X_OFFSET = BG_COLOR_FRAME_X_OFFSET + 52
LINE_COLOR_FRAME_Y_OFFSET = ACTION_ROW_Y_OFFSET + 2

SHOW_HIDE_FRAME_X_OFFSET = 64
SHOW_HIDE_FRAME_Y_OFFSET = STATUS_ROW_Y_OFFSET

FILL_WIDTH_FRAME_WIDTH = 72
FILL_WIDTH_FRAME_X_OFFSET = SHOW_HIDE_FRAME_X_OFFSET + FILL_WIDTH_FRAME_WIDTH
FILL_WIDTH_FRAME_Y_OFFSET = STATUS_ROW_Y_OFFSET

ALPHA_VALUES_FRAME_WIDTH = 160
ALPHA_VALUES_FRAME_X_OFFSET = FILL_WIDTH_FRAME_X_OFFSET + ALPHA_VALUES_FRAME_WIDTH
ALPHA_VALUES_FRAME_Y_OFFSET = STATUS_ROW_Y_OFFSET

VIEWER_DIMENSIONS_FRAME_WIDTH = 160
VIEWER_DIMENSIONS_FRAME_X_OFFSET = ALPHA_VALUES_FRAME_X_OFFSET + VIEWER_DIMENSIONS_FRAME_WIDTH
VIEWER_DIMENSIONS_FRAME_Y_OFFSET = STATUS_ROW_Y_OFFSET

CURSOR_LOCATION_FRAME_WIDTH = 150
CURSOR_LOCATION_FRAME_X_OFFSET = VIEWER_DIMENSIONS_FRAME_X_OFFSET + CURSOR_LOCATION_FRAME_WIDTH
CURSOR_LOCATION_FRAME_Y_OFFSET = STATUS_ROW_Y_OFFSET

